= Functions
:id: functions

This chapter describes the Modelica function construct.

== Function Declaration

A Modelica _function_ is a specialized class (see <<function-as-a-specialized-class>>) using the keyword `function`.
The body of a Modelica function is an algorithm section that contains procedural algorithmic code to be executed when the function is called, or alternatively an external function specifier (see <<external-function-interface>>).
Formal parameters are specified using the `input` keyword, whereas results are denoted using the `output` keyword.
This makes the syntax of function definitions quite close to Modelica class definitions, but using the keyword `function` instead of `class`.

[NOTE]
The structure of a typical function declaration is sketched by the following schematic function example:
[source,modelica]
----
function functionname
  input  TypeI1 in1;
  input  TypeI2 in2;
  input  TypeI3 in3 = defaultExpr_1 "Comment" annotation(...);
  ...
  output TypeO1 out1;
  output TypeO2 out2 = defaultExpr_2;
  ...
protected
  // local variables
  ...
algorithm
  // statements
  ...
end functionname;
----

Optional explicit default values can be associated with any input or output formal parameter through binding equations.
Comment strings and annotations can be given for any formal parameter declaration, as usual in Modelica declarations.

Explicit default values are shown for the third input parameter and the second output parameter in the example above.

All internal parts of a function are optional; i.e., the following is also a legal function:
[source,modelica]
----
function functionname
end functionname;
----

=== Ordering of Formal Parameters

The relative ordering between input formal parameter declarations is significant since that determines the matching between actual arguments and formal parameters at function calls with positional parameter passing.
Likewise, the relative ordering between the declarations of the outputs is significant since that determines the matching with receiving variables at function calls of functions with multiple results.
However, the declarations of the inputs and outputs can be intermixed as long as these internal orderings are preserved.

[NOTE]
Mixing declarations in this way is not recommended, however, since it makes the code hard to read.

.Example
[source,modelica]
----
function functionname
  output TypeO1 out1; // Intermixed declarations of inputs and outputs
  input TypeI1 in1; // not recommended since code becomes hard to read
  input TypeI2 in2;
  ...
  output TypeO2 out2;
  input TypeI3 in3;
  ...
end functionname;
----

=== Function Return-Statements

The `return` statement terminates the current function call (see <<function-call>>).
It can only be used in an algorithm section of a function.

[source,modelica]
----
return;
----

.Example
[source,modelica]
----
function findValue "Returns position of val or 0 if not found"
  input Integer x[:];
  input Integer val;
  output Integer index;
algorithm
  for i in 1:size(x,1) loop
    if x[i] == val then
      index := i;
      return;
    end if;
  end for;
  index := 0;
  return;
end findValue;
----

=== Inheritance of Functions

It is allowed for a function to inherit and/or modify another function following the usual rules for inheritance of classes (see <<inheritance-modification-and-redeclaration>>).

[NOTE]
For example, it is possible to modify and extend a `function` class to add default values for input variables.

A special case is defining a `function` as a short-class definition with modifiers for inputs inside a model.
These default values, unless overridden in the function call, will then be considered for variability similarly as if they were given in the function call (see <<function-variability>>).

.Example
Demonstrating the variability implications.
[source,modelica]
----
model M
  function foo
    input Real x1;
    input Real x2 = 2;
    output Real y;
  algorithm
    y := x1 + x2;
  end foo;
  Real x = time;
  function f1 = foo(x1 = x);
  constant Real z1 = f1(x1 = 2); // Legal, since 'x1' has a new value.
  constant Real z2 = f1(x2 = 1); // Illegal, since 'x' is seen as an argument.
end M;
----

== Function as a Specialized Class

The function concept in Modelica is a specialized class (see <<specialized-classes>>).

[NOTE]
The syntax and semantics of a function have many similarities to those of the `block` specialized class.
A function has many of the properties of a general class, e.g., being able to inherit other functions, or to redeclare or modify elements of a function declaration.

Modelica functions have the following restrictions compared to a general Modelica `class`:

* Each public component must have the prefix `input` or `output`.
* Input formal parameters are read-only after being bound to the actual arguments or default values, i.e., they shall not be assigned values in the body of the function.
* A function shall _not be used in connections_, shall not have _equations_, shall not have _initial algorithms_.
* A function can have at most _one algorithm_ section or _one external function interface_ (not both), which, if present, is the body of the function.
* A function may only contain components of the specialized classes `type`, `record`, `operator record`, and `function`; and it must not contain, e.g., `model`, `block`, `operator` or `connector` components.
* A function may not contain components of type `Clock`.
* The elements of a function shall not have prefixes `inner`, or `outer`.
* A function may have zero or one external function interface, which, if present, is the external definition of the function.
* For a function to be called in a simulation model, the function shall not be partial, and the output variables must be assigned inside the function either in binding equations or in an algorithm section, or have an external function interface as its body, or be defined as a function partial derivative.
  The output variables of a function should be computed.
  [NOTE]
  It is a quality of implementation how much analysis a tool performs in order to determine if the output variables are computed.
  A function _cannot contain_ calls to the Modelica _built-in operators_ `der`, `initial`, `terminal`, `sample`, `pre`, `edge`, `change`, `reinit`, `delay`, `cardinality`, `inStream`, `actualStream`, to the operators of the built-in package `Connections`, to the operators defined in <<synchronous-language-elements>> and <<state-machines>>, and is not allowed to contain `when`-statements.
* The dimension _sizes_ not declared with colon (`:`) of each array result or array local variable (i.e., a non-input component) of a function must be either given by the input formal parameters, or given by constant or parameter expressions, or by expressions containing combinations of those (see <<initialization-and-binding-equations-of-components-in-functions>>).
* For initialization of local variables of a function see <<initialization-and-binding-equations-of-components-in-functions>>.
* Components of a function will inside the function behave as though they had discrete-time variability.

Modelica functions have the following enhancements compared to a general Modelica `class`:

* Functions can be called (see <<function-call>>).
  * The calls can use a mix of positional and named arguments (see <<positional-or-named-input-arguments-of-functions>>).
  * Instances of functions have a special meaning (see <<functional-input-arguments-to-functions>>).
  * The lookup of the `function` class to be called is extended (see <<composite-name-lookup>>).
* A function can be _recursive_.
* A formal parameter or local variable may be initialized through a _binding_ (=) of a default value in its declaration (see <<initialization-and-binding-equations-of-components-in-functions>>).
  If a non-input component in the function uses a record class that contain one or more binding equations they are viewed as initialization of those component of the record component.
* A function is dynamically instantiated when it is called rather than being statically instantiated by an instance declaration, which is the case for other kinds of classes.
* A function may have an external function interface specifier as its body.
* A function may have a `return` statement in its algorithm section body.
* A function allows dimension sizes declared with colon (`:`) to be resized for non-input array variables (see <<flexible-array-sizes-and-resizing-of-arrays-in-functions>>).
* A function may be defined in a short function definition to be a function partial derivative.

== Pure Modelica Functions

Modelica functions are normally _pure_ which makes it easy for humans to reason about the code since they behave as mathematical functions, and possible for compilers to optimize.

* _Pure_ Modelica functions always give the same output values or errors for the same input values and only the output values influence the simulation result, i.e., is seen as equivalent to a mathematical map from input values to output values.
  Some input values may map to errors.
  Pure functions are thus allowed to fail by calling `assert`, or `ModelicaError` in C code, or dividing by zero.
  Such errors will only be reported when and if the function is called.
  _Pure_ Modelica functions are not assumed to be thread-safe.
* A Modelica function which does not have the _pure_ function properties is _impure_.

The declaration of functions follow these rules:

* Functions defined in Modelica (non-external) are _normally_ assumed to be pure (the exception is the deprecated case below), if they are impure they shall be marked with the `impure` keyword.
  They can be explicitly marked as `pure`.
  [NOTE]
  However, since functions as default are pure it is not recommended to explicitly declare them as `pure`.
* External functions must be explicitly declared with `pure` or `impure`.
* If a function is declared as `impure` any function extending from it shall be declared as `impure`.
* A deprecated semantics is that external functions (and functions defined in Modelica directly or indirectly calling them) without `pure` or `impure` keyword are assumed to be impure, but without any restriction on calling them.
  Except for the function `Modelica.Utilities.Streams.print`, a diagnostic must be given if called in a simulation model.

Calls of pure functions used inside expression may be skipped if the resulting expression will not depend on the possible returned value; ignoring the possibility of the function generating an error.

A call to a function with no declared outputs is assumed to have desired side-effects or assertion checks.

[NOTE]
A tool shall thus not remove such function calls, with exception of non-triggered assert calls.
A pure function, used in an expression or used with a non-empty left hand side, need not be called if the output from the function call do not mathematically influence the simulation result, even if errors would be generated if it were called.

[NOTE]
Comment 1: This property enables writing declarative specifications using Modelica.
It also makes it possible for Modelica compilers to freely perform algebraic manipulation of expressions containing function calls while still preserving their semantics.
For example, a tool may use common subexpression elimination to call a pure function just once, if it is called several times with identical input arguments.
However, since functions may fail we can, e.g., only move a common function call from inside a loop to outside the loop if the loop is run at least once.

[NOTE]
Comment 2: The Modelica translator is responsible for maintaining this property for pure non-external functions.
Regarding external functions, the external function implementor is responsible.
Note that external functions can have side-effects as long as they do not influence the internal Modelica simulation state, e.g., caching variables for performance or printing trace output to a log file.

With the prefix keyword `impure` it is stated that a Modelica function is _impure_ and it is only allowed to call such a function from within:

* Another function marked with the prefix `impure`.
* A `when`-equation.
* A `when`-statement.
* `pure(impureFunction(...))` -- which allows calling impure functions in any pure context.
  The wrapping in `pure(...)` only by-passes the purity checking of the callee `impureFunction`; the argument expressions of the function call are not affected.
* Initial equations and initial algorithms.
* Binding equations for components declared as parameter -- which is seen as syntactic sugar for having a parameter with `fixed=false` and the binding as an initial equation.
  [NOTE]
  Thus, evaluation of the same function call at a later time during simulation is not guaranteed to result in the same value as when the parameter was initialized, seemingly breaking the declaration equation.
* Binding equations for external objects.

It is an error if an impure function call is part of a systems of equations (including linear systems), even if called in agreement with the restrictions above.
The reason is that solving systems of equations generally requires expressions to be evaluated an unknown number of times.
This includes the special handling of `when initial()` during initialization.

There are two ways in which an impure function could be called in a system of equations, namely in the deprecated case of external functions assumed to be impure, and when using `pure(...)` to call an impure function from within a pure function.
The side-effect semantics of the function call are then undefined.
Specifically, the number of calls with external side-effects is unspecified.
However, for impure functions where the outputs only depend on the inputs the system of equations should be solved correctly.

[NOTE]
A tool is not allowed to perform any optimizations on function calls to an impure function, e.g., reordering calls from different statements in an algorithm or common subexpression elimination is not allowed.

By <<function-compatibility-or-function-subtyping-for-functions>>, it follows that an impure function can only be passed as argument to a function formal parameter of impure type.
A function having a formal function parameter that is `impure` must be marked `pure` or `impure`.

.Example
[source,modelica]
----
function evaluateLinear // pure function
  input Real a0;
  input Real a1;
  input Real x;
  output Real y;
algorithm
  y := a0 + a1*x;
end evaluateLinear;

impure function receiveRealSignal // impure function
  input HardwareDriverID id;
  output Real y;
external "C"
  y = receiveSignal(id);
end receiveRealSignal;
----

Examples of allowed optimizations of pure functions:
[source,modelica]
----
model M // Assume sin, cos, asin are pure functions with normal derivatives.
  input Real x[2];
  input Real w;
  Real y[2] = [cos(w), sin(w); -sin(w), cos(w)] * x;
  Real z[2] = der(y);
  Real a = 0 * asin(w);
end M;
----

A tool only needs to generate one call of the pure function `cos(w)` in the model `M` -- a single call used for both the two elements of the matrix, as well as for the derivative of that matrix.
A tool may also skip the possible error for `asin(w)` and assume that `a` is zero.

Examples of restrictions on optimizing pure functions:
[source,modelica]
----
  Real x =
    if noEvent(abs(x)) < 1 then
      asin(x) // Cannot move asin(x) out of if-branch.
    else
      0;
algorithm
  assertCheck(p, T); // Must call function
algorithm
  if b then
    y := 2 * someOtherFunction(x);
  end if;
  y := y + asin(x);
  y := y + someOtherFunction(x);
  // Cannot evaluate someOtherFunction(x) before asin(x) - unless b is true
  // The reason is that asin(x) may fail and someOtherFunction may hang,
  // and it might be possible to recover from this error.
----

== Function Call

Function classes and record constructors (see <<record-constructor-functions>>) and enumeration type conversions (see <<type-conversion-of-integer-to-enumeration-values>>) can be called as described in this section.

=== Positional or Named Input Arguments

A function call has optional positional arguments followed by zero, one or more named arguments, such as

[source,modelica]
----
f(3.5, 5.76, arg3=5, arg6=8.3);
----

The formal syntax of a function call (simplified by removing reduction expression, see <<reduction-expressions>>):

[source,grammar]
----
primary :
   component-reference function-call-args

function-call-args :
   "(" [ function-arguments ] ")"

function-arguments :
   function-argument [ "," function-arguments]
   | named-arguments

named-arguments: named-argument [ "," named-arguments ]

named-argument: IDENT "=" function-argument

function-argument : function-partial-application | expression
----

The interpretation of a function call is as follows: First, a list of unfilled slots is created for all formal input parameters.
If there are N positional arguments, they are placed in the first N slots, where the order of the parameters is given by the order of the component declarations in the function definition.
Next, for each named argument `identifier = expression`, the `identifier` is used to determine the corresponding slot.
The value of the argument is placed in the slot, filling it (it is an error if this slot is already filled).
When all arguments have been processed, the slots that are still unfilled are filled with the corresponding default value of the function definition.
The default values may depend on other inputs (these dependencies must be acyclical in the function) -- the values for those other inputs will then be substituted into the default values (this process may be repeated if the default value for that input depend on another input).
The default values for inputs shall not depend on non-input variables in the function.
The list of filled slots is used as the argument list for the call (it is an error if any unfilled slots still remain).

Special purpose operators with function syntax defined in the specification shall not be called with named arguments, unless otherwise noted.

The type of each argument must agree with the type of the corresponding parameter, except where the standard type coercion (see <<standard-type-coercion>>) can be used to make the types agree.
(See also <<scalar-functions-applied-to-array-arguments>> on applying scalar functions to arrays.)

.Example
Assume a function `RealToString` is defined as follows to convert a `Real` number to a `String`:
[source,modelica]
----
function RealToString
  input Real number;
  input Real precision = 6 "number of significantdigits";
  input Real length = 0 "minimum length of field";
  output String string "number as string";
  ...
end RealToString;
----

Then the following applications are equivalent:
[source,modelica]
----
RealToString(2.0);
RealToString(2.0, 6, 0);
RealToString(2.0, 6);
RealToString(2.0, precision=6);
RealToString(2.0, length=0);
RealToString(2.0, 6, precision=6); // error: slot is used twice
----

=== Functional Input Arguments

A functional input argument to a function is an argument of function type.
The declared type of such an input formal parameter in a function can be the type-specifier of a partial function that has no replaceable elements.
It cannot be the type-specifier of a record or enumeration (i.e., record constructor functions and enumeration type conversions are not allowed in this context).
Such an input formal parameter of function type can also have an optional functional default value.

.Example
[source,modelica]
----
function quadrature "Integrate function y = integrand(x) from x1 to x2"
  input Real x1;
  input Real x2;
  input Integrand integrand; // Integrand is a partial function, see below
  // With default: input Integrand integrand = Modelica.Math.sin;
  output Real integral;
algorithm
  integral := (x2 - x1) * (integrand(x1) + integrand(x2)) / 2;
end quadrature;

partial function Integrand
  input Real u;
  output Real y;
end Integrand;
----

A functional argument can be provided in one of the following forms to be passed to a scalar formal parameter of function type in a function call:

. as a function type-specifier (`Parabola` example below),
. as a function partial application (see <<function-partial-application>> below),
. as a function that is a component (i.e., a formal parameter of function type of the enclosing function),
. as a function partial application of a function that is a component (example in <<function-partial-application>> below).

In all cases the provided function must be function-compatible (see <<function-compatibility>>) with the corresponding formal parameter of function type.

.Example
A function as a positional input argument according to case 1 above:
[source,modelica]
----
function Parabola
  extends Integrand;
algorithm
  y := x * x;
end Parabola;
area = quadrature(0, 1, Parabola);
----

The `quadrature2` example below uses a function `integrand` that is a component as input argument according to case 3 above:
[source,modelica]
----
function quadrature2 "Integrate function y = integrand(x) from x1 to x2"
  input Real x1;
  input Real x2;
  input Integrand integrand; // Integrand is a partial function type
  output Real integral;
algorithm
  integral :=
    quadrature(x1, (x1 + x2) / 2, integrand) +
    quadrature((x1 + x2) / 2, x2, integrand);
end quadrature2;
----

==== Function Partial Application

A function partial application is similar to a function call with certain formal parameters bound to expressions, the specific rules are specified in this section and are not identical to the ones for function call in <<positional-or-named-input-arguments-of-functions>>.
A function partial application returns a partially evaluated function that is also a function, with the remaining not bound formal parameters still present in the same order as in the original function declaration.
A function partial application is specified by the `function` keyword followed by a function call to `func_name` giving named formal parameter associations for the formal parameters to be bound, e.g.:
[source,modelica]
----
function func_name(..., formal_parameter_name = expr, ...)
----

[NOTE]
Note that the keyword `function` in a function partial application differentiates the syntax from a normal function call where some parameters have been left out, and instead supplied via default values.

The function created by the function partial application acts as the original function but with the bound formal input parameters(s) removed, i.e., they cannot be supplied arguments at function call.
The binding occurs when the partially evaluated function is created.
A partially evaluated function is function-compatible (see <<function-compatibility>>) with the same function where all bound arguments are removed.

[NOTE]
Thus, for checking function type compatibility, bound formal parameters are ignored.

.Example
Function partial application as argument, positional argument passing, according to case 2 above:
[source,modelica]
----
model Test
  parameter Integer N;
  Real area;
algorithm
  area := 0;
  for i in 1:N loop
    area := area + quadrature(0, 1, function Sine(A = 2, w = i * time));
  end for;
end Test;

function Sine "y = Sine(x, A, w)"
  extends Integrand;
  input Real A;
  input Real w;
algorithm
  y := A * Modelica.Math.sin(w * x);
end Sine;
----

Call with function partial application as named input argument:
[source,modelica]
----
area :=
  area + quadrature(0, 1, integrand = function Sine(A = 2, w = i * time));
----

.Example
Function types are matching after removing the bound arguments `A` and `w` in a function partial application:
[source,modelica]
----
function Sine2 "y = Sine2(A, w, x)"
  input Real A;
  input Real w;
  input Real x; // Note: x is now last in argument list.
  output Real y;
algorithm
  y := A * Modelica.Math.sin(w * x);
end Sine2;
area = quadrature(0, 1, integrand = function Sine2(A = 2, w = 3));
----

The partially evaluated `Sine2` has only one argument: `x` -- and is thus type compatible with `Integrand`.

.Example
Function partial application of a function that is a component, according to case 4 above:
[source,modelica]
----
partial function SurfaceIntegrand
  input Real x;
  input Real y;
  output Real z;
end SurfaceIntegrand;

function quadratureOnce
  input Real x;
  input Real y1;
  input Real y2;
  input SurfaceIntegrand integrand;
  output Real z;
algorithm
  z := quadrature(y1, y2, function integrand(y = x));
  // This is according to case 4 and needs to bind the 2nd argument
end quadratureOnce;

function surfaceQuadrature
  input Real x1;
  input Real x2;
  input Real y1;
  input Real y2;
  input SurfaceIntegrand integrand;
  output Real integral;
algorithm
  integral :=
    quadrature(x1, x2,
      function quadratureOnce(y1 = y1, y2 = y2, integrand = integrand));
  // Case 2 and 3
end surfaceQuadrature;
----

=== Output Formal Parameters

A function may have more than one output component, corresponding to multiple return values.
The only way to use more than the first return value of such a function is to make the function call the right hand side of an equation or assignment.
In this case, the left hand side of the equation or assignment shall contain a list of component references within parentheses:

`(out1, out2, out3) = f(...);`

The component references are associated with the output components according to their position in the list.
Thus output component i is set equal to, or assigned to, component reference i in the list, where the order of the output components is given by the order of the component declarations in the function definition.
The type of each component reference in the list must agree with the type of the corresponding output component.

A function application may be used as expression whose value and type is given by the value and type of the first output component, if at least one return result is provided.

It is possible to omit left hand side component references and/or truncate the left hand side list in order to discard outputs from a function call.

[NOTE]
Optimizations to avoid computation of unused output results can be automatically deduced by an optimizing compiler.

.Example
Function `eigen` to compute eigenvalues and optionally eigenvectors may be called in the following ways:
[source,modelica]
----
ev = eigen(A); // calculate eigenvalues
x = isStable(eigen(A)); // used in an expression
(ev, vr) = eigen(A) // calculate eigenvectors
(ev,vr,vl) = eigen(A) // and also left eigenvectors
(ev,,vl) = eigen(A) // no right eigenvectors
----

The function may be defined as:
[source,modelica]
----
function eigen "calculate eigenvalues and optionally eigenvectors"
  input Real A[:, size(A,1)];
  output Real eigenValues[size(A,1),2];
  output Real rightEigenVectors[size(A,1),size(A,1)];
  output Real leftEigenVectors [size(A,1),size(A,1)];
algorithm
  // The output variables are computed separately (and not, e.g., by one
  // call of a Fortran function) in order that an optimizing compiler can
  // remove unnecessary computations, if one or more output arguments are
  // missing
  //   compute eigenvalues
  //   compute right eigenvectors using the computed eigenvalues
  //   compute left eigenvectors using the computed eigenvalues
end eigen;
----

The only permissible use of an expression in the form of a list of expressions in parentheses, is when it is used as the left hand side of an equation or assignment where the right hand side is an application of a function.

.Example
The following are illegal:
[source,modelica]
----
(x+1, 3.0, z/y) = f(1.0, 2.0); // Not a list of component references.
(x, y, z) + (u, v, w) // Not LHS of suitable eqn/assignment.
----

=== Initialization and Binding Equations

Components in a function can be divided into three groups:

* Public components which are input formal parameters.
* Public components which are output formal parameters.
* Protected components which are local variables, parameters, or constants.

When a function is called, components of the function do not have `start` attributes.
However, a binding equation (`= expression`) with an expression may be present for a component.

A binding equation for a non-input component initializes the component to this `expression` at the start of every function invocation (before executing the algorithm section or calling the external function).
These bindings must be executed in an order where a variable is not used before its binding equations has been executed; it is an error if no such order exists (i.e., the binding must be acyclic).

Binding equations can only be used for components of a function.
If no binding equation is given for a non-input component the variable is uninitialized (except for record components where modifiers may also initialize that component).
It is an error to use (or return) an uninitialized variable in a function.
Binding equations for input formal parameters are interpreted as default arguments, as described in <<positional-or-named-input-arguments-of-functions>>.

[NOTE]
It is recommended to check for use of uninitialized variables statically -- if this is not possible a warning is recommended combined with a run-time check.

[NOTE]
The properties of components in functions described in this section are also briefly described in <<function-as-a-specialized-class>>.

=== Flexible Array Sizes and Resizing of Arrays

[NOTE]
Flexible setting of array dimension sizes of arrays in functions is also briefly described in <<function-as-a-specialized-class>>.

A dimension size not specified with colon (`:`) for a non-input array component of a function must be given by the inputs or be constant.

.Example
[source,modelica]
----
function joinThreeVectors
  input Real v1[:],v2[:],v3[:];
  output Real vres[size(v1,1)+size(v2,1)+size(v3,1)];
algorithm
  vres := cat (1,v1,v2,v3);
end joinThreeVectors;
----

A non-input array component declared in a function with a dimension size specified by colon (`:`) and no binding equation, can change size according to these special rules:

* Prior to execution of the function algorithm the dimension size is zero.
* The entire array (without any subscripts) may be assigned with a corresponding array with arbitrary dimension size (the array variable is re-sized).

These rules also apply if the array component is an element of a record component in a function.

.Example
A function to collect the positive elements in a vector:
[source,modelica]
----
function collectPositive
  input Real x[:];
  output Real xpos[:];
algorithm
  for i in 1 : size(x, 1) loop
    if x[i] > 0 then
      xpos := cat(1, xpos, x[i:i]);
    end if;
  end for;
end collectPositive;
----

=== Automatic Vectorization

Functions with one scalar return value can be applied to arrays element-wise, e.g., if `A` is a vector of reals, then `sin(A)` is a vector where each element is the result of applying the function `sin` to the corresponding element in `A`.
Only `function` classes that are transitively non-replaceable (see <<transitively-non-replaceable>> and <<restrictions-on-base-classes-and-constraining-types-to-be-transitively-non-replaceable>>) may be called vectorized.

Consider the expression `f(arg1, ..., argn)`, an application of the function `f` to the arguments `arg1`, ..., `argn`.
Potential vectorization of this call is defined as follows.
For each passed argument, the type of the argument is checked against the type of the corresponding formal parameter of the function:

. If the types match, nothing is done.
. If the types do not match, and a type conversion can be applied, it is applied.
. If the types do not match, and no type conversion is applicable, the passed argument type is checked to see if it is an n-dimensional array of the formal parameter type.
  If it is not, the function call is invalid.
  If it is, we call this a _foreach argument_.
. For all foreach arguments, the number and sizes of dimensions must match.
  If they do not match, the function call is invalid.
. If no foreach argument exists, the function is applied in the normal fashion, and the result has the type specified by the function definition.
. The result of the function call expression is an n-dimensional array `e` with the same dimension sizes as the foreach arguments.
  Each element `e[i, ..., j]` is the result of applying `f` to arguments constructed from the original arguments in the following way:
  * If the argument is not a foreach argument, it is used as-is.
  * If the argument is a foreach argument, the element at index `[i, ..., j]` is used.

If more than one argument is an array, all of them have to be the same size, and they are traversed in parallel.

.Example
[source,modelica]
----
sin({a, b, c}) = {sin(a), sin(b), sin(c)} // argument is a vector
sin([a, b, c]) = [sin(a), sin(b), sin(c)] // argument may be a matrix
atan2({a, b, c}, {d, e, f}) = {atan2(a, d), atan2(b, e), atan2(c, f)}
----

This works even if the function is declared to take an array as one of its arguments.
If `pval` is defined as a function that takes one argument that is a `Real` vector and returns a `Real`, then it can be used with an actual argument which is a two-dimensional array (a vector of vectors).
The result type in this case will be a vector of `Real`.

[source,modelica]
----
pval([1,2;3,4]) = [pval([1,2]); pval([3,4])]
sin([1,2;3,4]) = [sin({1,2}); sin({3,4})]
  = [sin(1), sin(2); sin(3), sin(4)]
----

[source,modelica]
----
function add
  input Real e1, e2;
  output Real sum1;
algorithm
  sum1 := e1 + e2;
end add;
----

`add(1, [1,2,3])` adds one to each of the elements of the second argument giving the result `[2,3,4]`.
For built-in operators one can do this with `1 .+ [1,2,3]` but not with `1 + [1,2,3]`, because the rules for the built-in operators are more restrictive.

=== Empty Function Calls

An _empty_ function call is a call that does not return any results.

[NOTE]
An empty call is of limited use in Modelica since a function call without results does not contribute to the simulation, but it is useful to check assertions and in certain cases for desired side-effects (see <<pure-modelica-functions>>).

An empty call can occur either as a kind of "null equation" or "null statement".

.Example
The empty calls to `eigen()` are examples of a "null equation" and a "null statement":
[source,modelica]
----
equation
  Modelica.Math.Matrices.eigen(A); // Empty function call as an equation
algorithm
  Modelica.Math.Matrices.eigen(A); // Empty function call as a statement
----

== Built-in Functions

There are basically four groups of built-in functions in Modelica:

* Intrinsic mathematical and conversion functions (see <<numeric-functions-and-conversion-functions>>).
* Derivative and special operators with function syntax (see <<derivative-and-special-purpose-operators-with-function-syntax>>).
* Event-related operators with function syntax (see <<event-related-operators-with-function-syntax>>).
* Built-in array functions (see <<built-in-array-functions>>).

Note that when the specification references a function having the name of a built-in function it references the built-in function, not a user-defined function having the same name.

== Record Constructor Functions

Whenever a record is defined, a record constructor function with the same name and in the same scope as the record class is implicitly defined according to the following rules:

The declaration of the record is partially flattened including inheritance, modifications, redeclarations, and expansion of all names referring to declarations outside of the scope of the record to their fully qualified names.

[NOTE]
The partial flattening is performed in order to remove potentially conflicting `import` clauses in the record constructor function due to flattening the inheritance tree.

All record elements (i.e., components and local class definitions) of the partially flattened record declaration are used as declarations in the record constructor function with the following exceptions:

* Component declarations which do not allow a modification (such as `final parameter Real`) are declared as protected components in the record constructor function.
* Prefixes (`constant`, `parameter`, `final`, `discrete`, ...) of the remaining record components are removed.
* The prefix `input` is added to the public components of the record constructor function.

An instance of the record is declared as output parameter using a name not appearing in the record, together with a modification.
In the modification, all input parameters are used to set the corresponding record variables.

A record constructor can only be called if the referenced record class is found in the global scope, and thus cannot be modified.

[NOTE]
This allows constructing an instance of a record, with an optional modification, at all places where a function call is allowed.

.Example
[source,modelica]
----
  record Complex "Complex number"
    Real re "real part";
    Real im "imaginary part";
  end Complex;

  function add
    input Complex u, v;
    output Complex w(re = u.re + v.re, im = u.im + v.re);
  end add;

  Complex c1, c2;
equation
  c2 = add(c1, Complex(sin(time), cos(time));
----

In the following example, a convenient data sheet library of components is built up:
[source,modelica]
----
package Motors
  record MotorData "Data sheet of a motor"
    parameter Real inertia;
    parameter Real nominalTorque;
    parameter Real maxTorque;
    parameter Real maxSpeed;
  end MotorData;

  model Motor "Motor model" // using the generic MotorData
    MotorData data;
    ...
  equation
    ...
  end Motor;

  record MotorI123 = MotorData( // data of a specific motor
    inertia = 0.001,
    nominalTorque = 10,
    maxTorque = 20,
    maxSpeed = 3600) "Data sheet of motor I123";
  record MotorI145 = MotorData( // data of another specific motor
    inertia = 0.0015,
    nominalTorque = 15,
    maxTorque = 22,
    maxSpeed = 3600) "Data sheet of motor I145";
end Motors

model Robot
  import Motors.*;
  Motor motor1(data = MotorI123()); // just refer to data sheet
  Motor motor2(data = MotorI123(inertia = 0.0012));
  // data can still be modified (if no final declaration in record)
  Motor motor3(data = MotorI145());
  ...
end Robot;
----

Example showing most of the situations, which may occur for the implicit record constructor function creation.
With the following record definitions:
[source,modelica]
----
package Demo
  record Record1
    parameter Real r0 = 0;
  end Record1;

  record Record2
    import Modelica.Math.*;
    extends Record1;
    final constant Real c1 = 2.0;
    constant Real c2;
    parameter Integer n1 = 5;
    parameter Integer n2;
    parameter Real r1 "comment";
    parameter Real r2 = sin(c1);
    final parameter Real r3 = cos(r2);
    Real r4;
    Real r5 = 5.0;
    Real r6[n1];
    Real r7[n2];
  end Record2;
end Demo;
----

The following record constructor functions are implicitly defined (the name of the output, given in italic below, is not defined; it should be chosen to not cause any conflict):
[source,modelica]
----
package Demo
  function Record1
    input Real r0 = 0;
    output Record1 result(r0 = r0);
  end Record1;

  function Record2
    input Real r0 = 0;
    input Real c2;
    input Integer n1 = 5;
    input Integer n2;
    input Real r1 "comment"; // the comment also copied from record
    input Real r2 = Modelica.Math.sin(c1);
    input Real r4;
    input Real r5 = 5.0;
    input Real r6[n1];
    input Real r7[n2];
    output Record2 result(
      r0 = r0, c2 = c2, n1 = n1, n2 = n2,
      r1 = r1, r2 = r2, r4 = r4, r5 = r5, r6 = r6, r7 = r7);
  protected
    final constant Real c1 = 2.0; // referenced from r2
    final parameter Real r3 = Modelica.Math.cos(r2);
  end Record2;
end Demo;
----

and can be applied in the following way
[source,modelica]
----
Demo.Record2 r1 =
  Demo.Record2(r0 = 1, c2 = 2, n1 = 2, n2 = 3, r1 = 1, r2 = 2, r4 = 5, r5 = 5,
               r6 = {1, 2}, r7 = {1, 2, 3});
Demo.Record2 r2 =
  Demo.Record2(1, 2, 2, 3, 1, 2, 5, 5, {1, 2}, {1, 2, 3});
parameter Demo.Record2 r3 =
  Demo.Record2(c2 = 2, n2 = 1, r1 = 1, r4 = 4, r6 = 1 : 5, r7 = {1});
----

The above example is only used to show the different variants appearing with prefixes, but it is not very meaningful, because it is simpler to just use a direct modifier.

== Casting to Record

A constructor of a record `R` can be used to cast an instance m of a `model`, `block`, `connector` class `M` to a value of type `R`, provided that for each component defined in `R` (that do not have a default value) there is also a public component defined in `M` with identical name and type.
A nested record component of `R` is handled as follows, if the corresponding component of `M` is a `model`/`block`/`connector` a nested record constructor is called -- otherwise the component is used directly; and the resulting call/component is used as argument to the record constructor `R`.
If the corresponding component of `R` in `M` is a conditional component, it is an error.
The instance `m` is given as single (un-named) argument to the record constructor of `R`.
The interpretation is that `R(m)` is replaced by a record constructor of type `R` where all public components of `M` that are present in `R` are assigned to the corresponding components of `R`.
The record cast can be used in vectorized form according to <<scalar-functions-applied-to-array-arguments>>.

[NOTE]
The problem if `R` would be a conditional component is that the corresponding binding would be illegal since it is not a `connect`-equation.

[NOTE]
The record cast operation is uniquely distinguished from a record constructor call, because an argument of the record constructor cannot be a `model`, `block` or `connector` instance.

.Example
[source,modelica]
----
connector Flange
  Real phi;
  flow Real tau;
end Flange;

model Model1
  Real m1;
  Boolean b1;
  Flange flange;
end Model1;

model Model2
  Real r1;
  Real r2;
  Integer i2;
  Pin p1, p2;
  Model1 sub1;
  protected
  Integer i1;
  ...
end Model2;

record MyFlange
  Real tau;
end MyFlange;

record MyRecord1
  Boolean b1;
  MyFlange flange;
end MyRecord1;

record MyRecord2
  Real r1;
  Integer i2;
  MyRecord1 sub1;
end MyRecord2;

model Model
  Model2 s1;
  Model2 s2[2];
  MyRecord2 rec1 = MyRecord2(s1);
  MyRecord2 rec2[2] = MyRecord2(s2);
  ...
end Model;
// Model is conceptually mapped to
model ModelExpanded
  Model2 s1;
  Model2 s2[2];
  MyRecord2 rec1 = MyRecord2(r1=s1.r1, i2=s1.i2,
  sub1 = MyRecord1(b1=s1.sub1.b1,
  flange = MyFlange(tau=s1.sub1.flange.tau));
  MyRecord2 rec2[2] = {MyRecord2(r1=s2[1].r1, i2=s2[1].i2,
  sub1 = MyRecord1(b1=s2[1].sub1.b1,
  flange = MyFlange(tau=s1[1].sub1.flange.tau)),
  MyRecord2(r1=s2[2].r1, i2=s2[2].i2,
  sub1 = MyRecord1(b1=s2[2].sub1.b1,
  flange = MyFlange(tau=s2[2].sub1.flange.tau)}};
  ...
end ModelExpanded;
----

== Derivatives and Inverses of Functions

The annotations listed below are related to differentiation and closed-form inverses of functions.
A function declaration can have `derivative` annotations specifying derivative functions or preferably, for a function written in Modelica, use the `smoothOrder` annotation to indicate that the tool can construct the derivative function automatically.
Partial derivatives are not provided via annotations, but using a certain type of short function definition described in <<partial-derivatives-of-functions>>.

[cols="1,2,2",options="header"]
|===
|Annotation |Description |Details
|`smoothOrder` |Function smoothness guarantee |<<modelica:smoothOrder>>
|`derivative` |Provide function derivative |<<modelica:derivative>>
|`inverse` |Provide closed-form inverses |<<modelica:inverse>>
|===

See the original document for full details on the annotation syntax and semantics.

== External Function Interface

See the original document for details on external function interface, argument type mapping, return type mapping, annotations for external libraries and include files, utility functions, and external objects.
