== Annotations

Annotations are intended for storing extra information about a model, such as graphics, documentation or versioning, etc.
The standard annotations (that is, all annotations except the vendor-specific ones, see <<vendor-specific-annotations>>) shall only be used where their semantics is defined.
A Modelica tool is free to define and use other annotations, in addition to those defined here, according to <<vendor-specific-annotations>>.

Annotations are optional in the Modelica grammar, and when present, indicated using the `annotation` keyword, see `annotation-clause` in the grammar (<<expressions1>>).
The structure of the annotation content is the same as a class modification (`class-modification` in the grammar).
(For replaceable class declarations with a `constraining-clause` also refer to <<constraining-clause-annotations>>.)
The specification in this document defines the semantic meaning if a tool implements any of these annotations.

=== Notation for Annotation Definitions

Annotations are defined using the syntactic forms of Modelica component declarations and record definitions, with the following special semantics.
If the annotation is described by a component declaration, the annotation is used in the form of a value modifier for the same name.
If the annotation is described by a `record` _class_ the annotation is used in the form of a modifier for a `record` _component_ with the same name.

A declaration equation for a component or record member specifies a default to be used when no corresponding annotation is given.
An array record member without declaration equation and with size specified by colon (`:`) defaults to being empty.
Default behavior can also be specified in the text as an alternative to a declaration equation, or implicitly by saying _if specified_.
If the description states that the annotation only has an effect for specific values it implies that the default is a value that has no effect.
When there is no declaration equation and no other explanation of default behavior in the text for a record member, an annotation modifier for the record must contain a modifier for that member.

As all annotations are optional, component declaration annotations will always have default behavior.
The default behavior is either the implicit absence of any of the effects for defined values of the annotation, or explicitly defined as corresponding to one of the valid values.

When an annotation is defined with a component variability prefix (<<component-variability-prefixes-discrete-parameter-constant>>), this restricts the allowed variability of corresponding annotation modifiers analogously to the rules in <<variability-of-expressions>>.
If the annotation is declared as an `/*evaluable*/ parameter` the corresponding modifier is further restricted to be evaluable.
If the annotation is declared as a `/*literal*/ constant` the corresponding modifier is further restricted to be a literal value.

[example]
====
Since the semantics of an annotation comes from the interpretation as a modification, empty annotations have no impact at all.
For example, the following is allowed, but meaningless:
[source,modelica]
----
annotation(Dialog());
----
An annotation such as `annotation(Dialog)` is also meaningless, but deprecated according to <<semantic-restrictions-of-annotation-syntax>>.
====

=== Semantic Restrictions of Annotation Syntax

The syntactic form of annotations, `annotation-clause`, uses the generic `class-modification` in <<modification>>.
However, except where explicitly stated, the following constructs shall not be used in annotations:

* `final`. For instance, neither `final experiment(StopTime = 2.0)` nor `experiment(final StopTime = 2.0)` may be used to prevent that an extending model overrides the `StopTime` setting.
* `each`. When an annotation is given for an array component declaration, it applies to the array as a whole. Thus, neither should values be given in arrays matching the size of the declared component, nor should `each` be used express that a scalar value applies to each element of the array.
* `element-redeclaration` in the grammar. In particular, the keyword `redeclare` cannot be used.
* `element-replaceable` in the grammar. In particular the keywords `replaceable` and `constrainedby` cannot be used.
* An `element-modification` without `modification` is deprecated without exceptions. The meaning of such annotations has never been defined.

[example]
====
The following annotations are not merely meaningless, but deprecated:
[source,modelica]
----
annotation(
  Dialog,
  Dialog(colorSelector)
);
----
In particular, the effect of `colorSelector` is not the same as `colorSelector = true`, even though the latter is the only meaningful use of `colorSelector`.
====

=== Expression Evaluation Inside Annotations

This section describes some differences to the evaluation of expressions inside of annotations compared to normal evaluation rules outside of annotations.

==== Enumerations for Use in Annotations

Several annotations make use of dedicated enumeration types.
These enumeration types do not have the full status of being built-in types as, e.g., `StateSelect` (<<stateselect>>).
Instead, they are only in scope where expressions inside annotations are evaluated, shadowing any user-defined definitions with the same names.

[example]
====
The `smooth` attribute of a `Polygon` can be controlled through a model parameter, but the parameter cannot use the `Smooth` type directly:
[source,modelica]
----
model BezierParameter
  parameter Smooth smooth = Smooth.Bezier; // Error: Smooth is unknown here.
  parameter Boolean bezier = true;         // Fine.
  annotation(Icon(graphics = {
    Polygon(
      smooth = if bezier then Smooth.Bezier else Smooth.None,
      points = {{-50, -20}, {0, 30}, {50, -20}}
    )
  }));
end BezierParameter;
----
====

[NOTE]
====
When evaluating the expression _expr_ in the model `M`, one can imagine it being done as in
[source,modelica]
----
model M_annotation
  extends M;
  import AnnotationEnumerations.*;
  T result = expr;
end M_annotation;
----
where `AnnotationEnumerations` is a hidden package containing all enumeration types used in annotations, and _T_ is the expected type of the expression.
====

=== Vendor-Specific Annotations

A vendor may -- anywhere inside an annotation -- add specific, possibly undocumented, annotations which are not intended to be interpreted by other tools.
The semantic restrictions in <<semantic-restrictions-of-annotation-syntax>> are not enforced in vendor-specific annotations, giving vendors the full freedom of using the most general form of annotations.
The only requirement is that any tool shall save files with all vendor-specific annotations (and all annotations from this chapter) intact.
Two variants of vendor-specific annotations exist; one simple and one hierarchical.
Double underscore concatenated with a vendor name as initial characters of the identifier are used to identify vendor-specific annotations.

[example]
====
[source,modelica]
----
annotation(
  Icon(coordinateSystem(extent = {{-100, -100}, {100, 100}}),
       graphics = {__NameOfVendor(Circle(center = {0, 0}, radius = 10))}));
----
This introduces a new graphical primitive `Circle` using the hierarchical variant of vendor-specific annotations.
[source,modelica]
----
annotation(
  Icon(coordinateSystem(extent = {{-100, -100}, {100, 100}}),
       graphics = {Rectangle(extent = {{-5, -5}, {7, 7}},
                             __NameOfVendor_shadow = 2)}));
----
This introduces a new attribute `__NameOfVendor_shadow` for the `Rectangle` primitive using the simple variant of vendor-specific annotations.
====

=== Documentation

The `Documentation` annotation has the following contents, where the `info` and `revisions` annotations are described in <<annotation-info-revisions>>, and the `figures` annotation is described in <<annotations-for-figures>>:
[source,modelica]
----
record Documentation
  /*literal*/ constant String info = "" "Description of the class";
  /*literal*/ constant String revisions = "" "Revision history";
  Figure[:] figures; "Simulation result figures";
  /*literal*/ constant String[:] styleSheets "Style sheets for documentation";
end Documentation;
----

The `styleSheets` may also be given as a single string, see <<style-sheets>>.

How the tool interprets the information in `Documentation` is unspecified.

==== Class Description and Revision History

Inside the `Documentation` annotation, the `info` annotation gives a textual description of the class, and the `revisions` annotation gives a revision history.

[NOTE]
====
The `revisions` documentation may be omitted in printed documentation.
====

If the string starts with the tag `<html>` or `<HTML>`, the entire string is HTML encoded (assumed to end with `</html>` or `</HTML>`, but to be rendered as HTML even if the end-tag is missing).
Otherwise, the entire string is rendered as is.
HTML encoded content may contain links.
Modelica URIs may be used to refer to external resources (see <<external-resources>>), as well as to refer to Modelica classes, e.g.,
[source,modelica]
----
<a href="modelica:/MultiBody.Tutorial">MultiBody.Tutorial</a>
----

Together with scheme `Modelica` the (URI) fragment specifiers `#diagram`, `#info`, `#text`, `#icon` may be used to reference different layers.
User-defined fragment specifiers (anchors) may also be used, and they may be renamed when generating HTML (in particular to avoid collisions).
Example:
[source,modelica]
----
<a href="modelica:/MultiBody.Joints.Revolute#info">Revolute</a>
----

===== Style Sheets

Inside the `Documentation` annotation, each element of the `styleSheets` annotation array specifies a cascading style sheet.
The style sheets are used when displaying the `info` and `revisions` annotations found in the `Documentation` annotations of the package.
The `styleSheets` annotation is only considered for top-level packages, and applies to the entire package.
The style sheets will be cascaded in the given order.
Specifying just a string for `styleSheets` has the same meaning as specifying a singleton array containing the string.

[NOTE]
====
It is recommended to use `class` and `id` selectors with a `$NameOfLibrary$-` prefix to avoid collisions when the content is included in a larger context.
====

The style sheet rules should not use type or universal selectors, due to possible interference with tool-specific styling.

Vendors should use a `$NameOfVendor$-` prefix to style vendor generated HTML content surrounding the user provided documentation.
If tools want to give users (of that tool) the possibility to override the tool-specific CSS they can document that.
The prefix is used to avoid this happening by accident.

==== Figures

Inside the `Documentation` annotation, each element of the `figures` annotation array has the following content:
[source,modelica]
----
record Figure
  /*literal*/ constant String title = "" "Title meant for display";
  /*literal*/ constant String identifier = "" "Identifier meant for programmatic access";
  /*literal*/ constant String group = "" "Name of figure group";
  /*literal*/ constant Boolean preferred = false "Automatically display figure after simulation";
  Plot[:] plots "Plots";
  /*literal*/ constant String caption = "" "Figure caption";
end Figure;
----

A `Figure` is a graphical container that can contain several `plots` described by `Plot` annotations:
[source,modelica]
----
record Plot
  /*literal*/ constant String title "Title meant for display";
  /*literal*/ constant String identifier = "" "Identifier meant for programmatic access";
  Curve[:] curves "Plot curves";
  /*literal*/ constant Axis x "X axis properties";
  /*literal*/ constant Axis y "Y axis properties";
end Plot;
----

A `Plot` can contain several `curves`, see <<plot-curves>>, that all share a common `x` and `y` axis with properties described in <<axis-properties>>.

Both `Figure` and `Plot` can have an optional title.
When the `Figure` `title` is the empty string (the default), the tool must produce a non-empty title based on the figure content.
On the other hand, the `Plot` `title` has a tool-dependent default, but the default may be the empty string.
When the `Plot` `title` is the empty string, no title should be shown.
The plot title is not to be confused with the plot _label_ which is never empty, see below.
Variable replacements, as described in <<variable-replacements>>, can be used in the `title` of `Figure` and `Plot`.

The `identifier` in `Figure` and `Plot` is a `String` identifier, and is intended to identify the `Figure` and `Plot` for programmatic access.
The `figures` annotation is inherited in the sense that each class has a collection of figures comprised by the contents of the `figures` annotation in the class itself, as well as the `figures` annotations from any base classes.
A `Figure` must be uniquely identified by its `identifier` and a class having it in its collection.
This means that a `Figure` `identifier` must be unique among all `Figure` annotations within the same `figures` annotation as well as among all `figures` annotations from inherited classes.
A `Plot` `identifier` on the other hand is only required to be unique among the `plots` in the the same `Figure` annotation.
If an `identifier` is an empty string it cannot be used for programmatic access and is exempt from the uniqueness requirements.

[NOTE]
====
For `Figure`, this makes it possible to reference the plot from a tool-specific scripting environment.
For `Plot`, this makes it possible to reference the plot in the figure caption, which becomes useful when the `Figure` contains more than one `Plot`.
====

// henrikt-ma 2020-06: Once there is Modelica URI support for referring to a figure in the collection of a class, it will be easier to explain
// the following statement.
Even though a `Figure` annotation can be shared through inheritance between classes in a class hierarchy, note that each simulated class provides its own data to be displayed in the figure.

Every `Plot` has an automatically generated _label_ which is required to be shown as soon as at least one `Plot` in the `Figure` has an `identifier`.
A tool is free to choose both labeling scheme (such as _a_, _b_, ..., or _i_, _ii_, ...), placement in the plot, and styling in the plot itself as well as in other contexts.

When a `Figure` defines a non-empty `group`, it is used to organize figures similar to how `group` is used in the `Dialog` annotation (see <<annotations-for-the-graphical-user-interface>>).
However, leaving `group` at the default of an empty string does not mean that a group will be created automatically, but that the figure resides outside of any group.
The `group` is both the key used for grouping, and the name of the group for display purposes.

The `preferred` attribute of `Figure` indicates whether the figure should be given preference when automatically determining which figures to show, and a class may define any number of `preferred` figures.
For example, a tool might choose to automatically show all preferred figures when the class is simulated.

The `caption` attribute of `Figure` can use the restricted form of text markup described in <<text-markup-in-captions>> as well as the variable replacements described in <<variable-replacements>>.

===== Axis Properties

Properties may be defined for each `Plot` axis (see also annotation index: Axis):

[source,modelica]
----
record Axis
  /*literal*/ constant Real min "Axis lower bound, in 'unit'";
  /*literal*/ constant Real max "Axis upper bound, in 'unit'";
  /*literal*/ constant String unit = "" "Unit of axis tick labels";
  /*literal*/ constant String label "Axis label";
  /*literal*/ constant AxisScale scale = Linear() "Mapping between axis values and position on axis"
end Axis;
----

When an axis bound is not provided, the tool computes one automatically.

A non-empty `unit` shall match `unit-expression` in <<unit-expressions>>.
An empty `unit` means that the axis is unitless, and each expression plotted against it may use its own unit determined by the tool.
The tool is responsible for conveying the information about choice of unit for the different variables, for instance by attaching this information to curve legends.

The Modelica tool is responsible for showing that values at the axis tick marks are expressed in `unit`, so the axis `label` shall not contain this information.

[NOTE]
When `unit` is empty, and axis bounds are to be determined automatically, a natural choice of unit could be the variable's `displayUnit`.
When axis bounds are specified by the user, on the other hand, a tool may choose a unit for the variable such that the range of the variable values (expressed in the chosen unit) fit nicely with the range of the unitless axis.

If a tool does not recognize the `unit`, it is recommended to issue a warning and treat the `unit` as if it was empty, as well as ignore any setting for `min` and `max`.

When `label` is not provided, the tool produces a default label.
Providing the empty string as `label` means that no label should be shown.
Variable replacements, as described in <<variable-replacements>>, can be used in `label`.
The Modelica tool is responsible for showing the unit used for values at the axis tick marks, so the axis `label` shall not contain the unit.

The type of `scale` is defined as an empty partial record:

[source,modelica]
----
partial record AxisScale
end AxisScale;
----

The standardized annotations extending from `AxisScale` are `Linear` and `Log`, but it is also allowed to use a vendor-specific annotation.

Use `Linear` for a linear mapping between axis values and position on axis:

[source,modelica]
----
record Linear
  extends AxisScale;
end Linear;
----

Use `Log` for a logarithmic mapping between axis values and position on axis:

[source,modelica]
----
record Log
  extends AxisScale;
  /*literal*/ constant Integer base(min = 2) = 10;
end Log;
----

The `base` of a `Log` scale determines preferred positions of major axis ticks.
It is not required that the presentation of axis tick labels reflect the `base` setting.
For example, when `base` is 10, major axis ticks should preferrably be placed at integer powers of 10, and natural alternatives that a tool may use for major axis tick labels could look like $0.001$ or $10^{-3}$.
Under some circumstances, such as when the axis range does not span even a single order of magnitude, a tool may disregard the preference in order to get useful axis ticks.

[example]
====
A _symmetric log_ axis scale is sometimes used for axes spanning across several orders of magnitude of both positive and negative values.
Details vary, but the mapping from value to linear position along axis is some variation of $y \mapsto \operatorname{sign}(y)\, \operatorname{log}(1 + \frac{\abs{y}}{10^{\alpha}})$.
A tool may implement this as a vendor-specific axis scale:

[source,modelica]
----
Axis(
  min = -1e5, max = 1e5,
  scale = __NameOfVendor_symlog(1),
)
----
====

===== Plot Curves

The actual data to plot is specified in the `curves` annotationindex:Curve of a `Plot`:
[source,modelica]
----
record Curve
  expression x = time "X coordinate values";
  expression y "Y coordinate values";
  /*literal*/ constant String legend "Legend";
  /*literal*/ constant Integer zOrder = 0 "Drawing order control";
end Curve;
----

The mandatory `x` and `y` expressions are restricted to be result references in the form of `result-reference` in the grammar (see <<expressions1>>), referring to a scalar variable (or a derivative thereof) or `time`.
It is an error if `x` or `y` does not designate a scalar result.
If `x` or `y` is a derivative, `der(v, n)`, then n must not exceed the maximum amount of differentiation applied to `v` in the model.
A diagnostic is recommended in case the simulation result is missing a trajectory for a valid result reference.

[NOTE]
====
While the syntax for referring to a second order derivative is `der(v, 2)`, the appearance is left for tools to decide.
For example, a tool might choose to present this as `der(der(v))`.
====

When the `unit` of an `Axis` is non-empty, it is an error if the unit of the corresponding `x` or `y` expression (i.e., a variable's `unit`, or second for `time`) is incompatible with the axis unit.

When `legend` is not provided, the tool produces a default based on `x` and/or `y`.
Providing the empty string as `legend` means that the curve shall be omitted from the plot legend.
Variable replacements, as described in <<variable-replacements>>, can be used in `legend`.
The order of presentation within the plot legend corresponds to order of appearance in the `curves` of a `Plot`.

The `zOrder` gives control over drawing order, with higher values corresponding to closer to front.
Ties are resolved using order of appearance in the `curves` of a `Plot`, with later appearance corresponding to closer to front.

===== Escape Sequences

In an attribute inside a figure where the variable replacements of <<variable-replacements>> or the text markup of <<text-markup-in-captions>> can be used, the following use of text markup escape sequences applies.
These escape sequences are applied after the application of other markup, and are not applied at all inside some of the other markup, see details for the respective markup.

The percent character `%` shall be encoded `%%`.
The following are all the recognized escape sequences:

[cols="c,c,l",options="header"]
|===
|Sequence |Encoded character |Comment
|`%%` |`%` |Only way to encode character.
|`%]` |`]`  |Prevents termination of markup delimited by `[$\ldots$]`.
|===

[NOTE]
====
With the percent character being encoded as `%%`, the behavior of `%` appearing in any other way than the escape sequences above, for variable replacement (see <<variable-replacements>>), or for the text markup (see <<text-markup-in-captions>>) is undefined, and thus possible to define in the future without breaking backward compatibility.
====

===== Vendor-Specific Markup

Vendor-specific markup takes the form `__$nameOfVendor_{1}($data_{1}$)...__$nameOfVendor_{n}($data_{n}$)`, where n ≥ 1.
It is only allowed as part of constructs described in <<variable-replacements>> and <<text-markup-in-captions>>, where it will be denoted by vendorSpecificMarkup.
The nameOfVendor consists of only digits and letters, and shall only convey the name of the vendor defining the meaning of the associated data.
Text markup escape sequences don't apply inside the data, implying that it cannot contain the closing parenthesis, `)`.
A tool which does not understand any of the vendor-specific meanings will always be able to safely ignore all vendor-specific markup.

===== Variable Replacements

In the places listed in <<attributes-with-variable-replacements>> where text for display is defined, the final value of a result variable can be embedded by referring to the variable as `%{inertia1.w}`.
This is similar to the `Text` graphical primitive in <<text>>.

.Attributes that can use variable replacements.
[cols="l,l",options="header"]
|===
|Attribute |Annotation
|`title`   |`Figure` and `Plot`
|`caption` |`Figure`
|`legend`  |`Curve`
|`label`   |`Axis`
|===

In `%{variable}`, text markup escape sequences don't apply inside the variable, which has the form of `result-reference`.
This means that a complete `result-reference` shall be scanned before looking for the terminating closing brace.

[example]
====
The variable replacement `%{'%%'}` references the variable `'%%'`, not the variable `'%'`.
====

[example]
====
The variable replacement `%{foo . '}bar{'}` makes a valid reference to the variable `foo.'}bar{'`.
====

Note that expansion to the final value means that expansion is not restricted to parameters and constants, so that values to be shown in a caption can be determined during simulation.

[NOTE]
====
By design, neither `%class` nor `%name` is supported in this context, as this information is expected to already be easily accessible (when applicable) in tool-specific ways.
(Titles making use of `%class` or `%name` would then only lead to ugly duplication of this information.)
====

Vendor-specific markup can be added to a variable replacement in the form `%vendorSpecificMarkup{variable}`.
The vendor-specific markup must not fundamentally alter the meaning of the variable replacement, in order to ensure that a tool can safely ignore all vendor-specific markup and still obtain a result that fits the current context.

[example]
====
One application of vendor-specific markup for variable replacement is to prototype a feature that can later be turned into standardized format control.
For example, the replaced variable may have an automatically inferred unit, but no `displayUnit`-attribute.
The tool vendor AVendor could then describe a selection of display unit with `%__AVendor(?displayUnit=mm){integrator1.y}`.
Later, if this would become supported by standard variable replacement, it might take the form of something like `%{integrator1.y?displayUnit=mm}` instead.
====

===== Text Markup in Captions

In addition to variable replacements, a very restricted form of text markup is used for the `caption`.
Note that the text markup escape sequences described in <<text-markup-escape-sequences>> generally apply inside `caption`, with one exception given below for links.

Links take the form `%[text](link)`, where the `[text]` part is optional, and text markup escape sequences don't apply inside the link.
The link can be in either of the following forms, where the interpretation is given by the first matching form:
* A `variable:id`, where id is a component reference in the form of `result-reference` in the grammar, such as `inertia1.w`.
* A `plot:id`, where id is the identifier of a `Plot` in the current `Figure`.
* A URI. Well established schemes such as `https://github.com/modelica` or `modelica:/Modelica`, as well as lesser known schemes may be used.
  (A tool that has no special recognition of a scheme can try sending the URI to the operating system for interpretation.)

When `[text]` is omitted, a Modelica tool is free to derive a default based on the link.

[NOTE]
====
Note that for the character `]` to appear in text, it needs to be encoded as the escape sequence `%]`, or it would be interpreted as the terminating delimiter of the `[text]`.

Similarly, the closing parenthesis `)` must be handled with care in link in order to not be interpreted as the terminating delimiter of the `(link)`.
* For a `variable:`, no special treatment is needed, as the component reference syntax of the id allows parentheses to appear without risk of misinterpretation inside a quoted identifier.
  For example, `%(variable:'try)me!')` has a parenthesis in `'try)me!'` that must not be mistaken for the end of the `(link)`.
* For a `plot:`, there is currently no way to reference a plot with `)` in its `identifier`.
* For a URI, a closing parenthesis must be URL encoded in order to not be interpreted as the end of the `(link)`.
  For example, the URL in `%(http://example.org/(tryme))` is just `http://example.org/(tryme`, and the entire link is followed by a stray closing parenthesis.
  To make it work, one has to use URL encoding: `%(http://example.org/%28tryme%29)` (using URL encoding of the opening parenthesis just for symmetry, and note that the `%` of the percent-encoded sequences are not subject to text markup escape sequences).
====

The styling of the link text, as well as the link action, is left for each Modelica tool to decide.

[NOTE]
====
For example, `%(variable:inertia1.w)` could be displayed as the text `inertia1.w` formatted with upright monospaced font, and have a pop-up menu attached with menu items for plotting the variable, setting its start value, or investigating the equation system from which it is solved.
On the other hand, `%[angular velocity](variable:inertia1.w)` could be formatted in the same style as the surrounding text, except some non-intrusive visual clue about it being linked.
====

[NOTE]
====
Note that link is currently not allowed to be a URI reference, i.e., a URI or a relative reference such as `#foo`.
This is due to to the current inability to define a base URI referencing the current figure.
Once this becomes possible, the URI form of link may be changed into a URI reference.
====

Vendor-specific markup can be added to a link in the form `%[text]vendorSpecificMarkup(link)`.
The vendor-specific markup must not fundamentally alter the appearance of the link, in order to ensure that a tool can safely ignore all vendor-specific markup and still obtain a result that fits the current context.

[example]
====
The HTML `<a>` tag has several attributes with potential application to links, such as `target`.
This attribute serves a natural purpose if the display of figures is integrated with the display of documentation.
The tool vendor AVendor could map the HTML feature to Modelica in the form `%__AVendor(?target=_blank)(modelica:/Modelica#info)`.
====

A sequence of one or more newlines (encoded either literally or using the `\n` escape sequence) means a paragraph break.
(A line break within a paragraph is not supported, and any paragraph break before the first paragraph or after the last paragraph has no impact.)

Vendor-specific markup for alternative content takes the form `%vendorSpecificMarkup[text]`.
The vendor-specific markup must not fundamentally alter the appearance of the text, in order to ensure that a tool can safely ignore all vendor-specific markup and still obtain a result that fits the current context.

[example]
====
One application of vendor-specific alternative content is to prototype a feature that can later be turned into standardized markup.
For example, say that the tool AVendor wants to generalize the variable replacements such that the duration of a simulation can be substituted into a caption.
During the development, this could be represented as the vendor-specific markup `%__AVendor(?duration)[10 s]`, if the simulation has a duration of 10 seconds at the time of writing the caption.
When AVendor renders this, it ignores the text `10 s` and just displays the actual duration instead.
Later, if this would become supported by standard markup, it might take the form of something like `%{experiment:duration}` instead (note that `experiment:duration` is not in the form of a component reference, avoiding conflict with current use of variable replacements).

In a similar way, vendor-specific alternative content can be used to prototype a link for future inclusion in the link markup (either by extending the meaning of Modelica URIs, or by introducing another pseudo-scheme similar to `variable:`).
This is an example where the vendor-specific markup could make use of the text (for link text) together with the vendor-specific data (describing the actual link).
====
